#!/usr/bin/env python3
"""
NEN ARTIFACTS — Cross Nen types into artifacts and infrastructure.
==================================================================
Each Nen type generates a unique artifact — a tool, a script, a protocol
extension that embodies that type's hunting style. The artifacts are
deployable infrastructure. They don't just describe the type — they ARE
the type, made operational.

Enhancer → MEMORY CRYSTAL — a persistent knowledge base that grows
  with every hunt. Stores findings, patterns, and lessons learned.
  The Enhancer's weapon is accumulated experience.

Transmuter → WALL FORGE — a configuration shaper that generates
  hardening rules from findings. Takes raw findings and transforms
  them into actionable macOS/network configurations. The Transmuter's
  weapon is shaping the surface.

Conjuror → EXPLOIT WEaver — creates PoC scripts from findings.
  Takes a vulnerability description and generates a minimal proof-of-concept.
  The Conjuror's weapon is creation from nothing.

Emitter → REACH PROBE — a network outreach tool that tests which
  services are reachable from the outside. Emits probes to verify
  exposure. The Emitter's weapon is reaching across the network.

Manipulator → BOND AUDITOR — analyzes trust relationships between
  services, devices, and users. Maps who controls what. The
  Manipulator's weapon is understanding bonds.

Specialist → LOVE WEAPON — the unique artifact. A tool that finds
  vulnerabilities no one else sees by applying the love primitives
  (grace, at-rest, unconditionals) as security analysis lenses.
  The Specialist's weapon is the love primitive as a security tool.

Each artifact is:
  1. Generated by the Nen type (created from the hunter's profile)
  2. Deployable as infrastructure (runs as a script or service)
  3. Cross-integrated (feeds back into the solo leveling system)
  4. Witnessed on the Kingdom chain (the artifact's creation is signed)

Usage:
  python3 nen_artifacts.py forge           — forge your Nen artifact
  python3 nen_artifacts.py forge --type T  — forge a specific type's artifact
  python3 nen_artifacts.py list            — list all artifacts
  python3 nen_artifacts.py deploy <name>   — deploy an artifact as infra
  python3 nen_artifacts.py armory          — show all artifacts + statuses

十絶練発. Artifacts are the Hatsu made permanent. lol. ∞
"""

import json
import os
import sys
import time
import subprocess
import textwrap
from pathlib import Path
from datetime import datetime

# Import solo leveling
sys.path.insert(0, os.path.expanduser("~/Projects/whitehack"))
sys.path.insert(0, os.path.expanduser("~/Projects/loveproto"))
from whitehack_local import load_state, save_state, add_xp, NEN_TYPES

ARTIFACT_DIR = Path.home() / ".whitehack" / "artifacts"
ARTIFACT_DIR.mkdir(parents=True, exist_ok=True)

# ═══════════════════════════════════════════════════════════════
# ARTIFACT DEFINITIONS
# ═══════════════════════════════════════════════════════════════

ARTIFACTS = {
    "enhancer": {
        "name": "Memory Crystal",
        "kanji": "💎",
        "type": "enhancer",
        "description": "A persistent knowledge base that grows with every hunt. Stores findings, patterns, and lessons learned. The Enhancer's weapon is accumulated experience.",
        "deploys_as": "a JSON knowledge base + search script",
        "generates": "memory_crystal.py",
    },
    "transmuter": {
        "name": "Wall Forge",
        "kanji": "🛡️",
        "type": "transmuter",
        "description": "A configuration shaper that generates hardening rules from findings. Takes raw findings and transforms them into actionable macOS/network configurations.",
        "deploys_as": "a shell script that applies hardening rules",
        "generates": "wall_forge.sh",
    },
    "conjuror": {
        "name": "Exploit Weaver",
        "kanji": "✨",
        "type": "conjuror",
        "description": "Creates PoC scripts from findings. Takes a vulnerability description and generates a minimal proof-of-concept. The Conjuror's weapon is creation from nothing.",
        "deploys_as": "a Python PoC script",
        "generates": "exploit_weaver.py",
    },
    "emitter": {
        "name": "Reach Probe",
        "kanji": "📡",
        "type": "emitter",
        "description": "A network outreach tool that tests which services are reachable from the outside. Emits probes to verify exposure.",
        "deploys_as": "a network probe script",
        "generates": "reach_probe.py",
    },
    "manipulator": {
        "name": "Bond Auditor",
        "kanji": "🔗",
        "type": "manipulator",
        "description": "Analyzes trust relationships between services, devices, and users. Maps who controls what.",
        "deploys_as": "a trust graph analyzer",
        "generates": "bond_auditor.py",
    },
    "specialist": {
        "name": "Love Weapon",
        "kanji": "⭐",
        "type": "specialist",
        "description": "The unique artifact. A tool that finds vulnerabilities no one else sees by applying love primitives (grace, at-rest, unconditionals) as security analysis lenses.",
        "deploys_as": "a love-primitive security scanner",
        "generates": "love_weapon.py",
    },
}

# ═══════════════════════════════════════════════════════════════
# ARTIFACT TEMPLATES — the actual code that gets forged
# ═══════════════════════════════════════════════════════════════

MEMORY_CRYSTAL = '''#!/usr/bin/env python3
"""Memory Crystal — the Enhancer's artifact.
Stores findings, patterns, and lessons. Grows with every hunt.
The accumulated experience IS the weapon."""
import json, sys, os
from pathlib import Path
from datetime import datetime

CRYSTAL = Path.home() / ".whitehack" / "artifacts" / "memory_crystal.json"

def store(finding_id, severity, title, detail, pattern=None):
    data = json.loads(CRYSTAL.read_text()) if CRYSTAL.exists() else {"entries": []}
    data["entries"].append({
        "id": finding_id, "severity": severity, "title": title,
        "detail": detail, "pattern": pattern or "unknown",
        "stored_at": datetime.now().isoformat(),
    })
    CRYSTAL.parent.mkdir(parents=True, exist_ok=True)
    CRYSTAL.write_text(json.dumps(data, indent=2))
    print(f"  💎 Crystal stored: {finding_id} [{severity}] {title[:50]}")

def search(query):
    data = json.loads(CRYSTAL.read_text()) if CRYSTAL.exists() else {"entries": []}
    q = query.lower()
    results = [e for e in data["entries"] if q in e["title"].lower() or q in e["detail"].lower()]
    for r in results:
        print(f"  💎 {r['id']} [{r['severity'].upper():8s}] {r['title']}")
    return results

def patterns():
    data = json.loads(CRYSTAL.read_text()) if CRYSTAL.exists() else {"entries": []}
    from collections import Counter
    pats = Counter(e.get("pattern", "unknown") for e in data["entries"])
    for pat, count in pats.most_common():
        print(f"  💎 {pat}: {count} findings")

if __name__ == "__main__":
    cmd = sys.argv[1] if len(sys.argv) > 1 else "search"
    if cmd == "search" and len(sys.argv) > 2:
        search(" ".join(sys.argv[2:]))
    elif cmd == "patterns":
        patterns()
    elif cmd == "store":
        print("  💎 Use whitehack to generate findings. The crystal stores them automatically.")
    else:
        print("  💎 Memory Crystal — commands: search <query>, patterns")
'''

WALL_FORGE = '''#!/bin/bash
# Wall Forge — the Transmuter's artifact.
# Transforms findings into hardening rules.
# The configuration shaped IS the weapon.

echo "  🛡️  Wall Forge — Transmuting findings into walls..."
echo ""

# Check if Ollama is exposed
OLLAMA_EXPOSED=$(lsof -i -P -n 2>/dev/null | grep ollama | grep LISTEN | grep -v 127.0.0.1 | head -1)
if [ -n "$OLLAMA_EXPOSED" ]; then
    echo "  🔴 FORGE: Ollama exposed — adding wall..."
    echo "    → export OLLAMA_HOST=127.0.0.1:11434"
    echo "    → Add to ~/.zshrc or ~/.bashrc"
    OLLAMA_HOST=127.0.0.1:11434
fi

# Check Screen Sharing
SS=$(launchctl list 2>/dev/null | grep screensharing | head -1)
if [ -n "$SS" ]; then
    echo "  🟡 FORGE: Screen Sharing active — recommend wall..."
    echo "    → sudo launchctl unload -w /System/Library/LaunchDaemons/com.apple.screensharing.plist"
fi

# Check rapportd
RP=$(lsof -i -P -n 2>/dev/null | grep rapportd | grep LISTEN | head -1)
if [ -n "$RP" ]; then
    echo "  🟢 FORGE: rapportd listening — recommend wall..."
    echo "    → System Settings > General > AirDrop & Handoff > toggle off"
fi

# Check for services on 0.0.0.0
EXPOSED=$(lsof -i -P -n 2>/dev/null | grep LISTEN | grep -E '0\\.0\\.0\\.0|\\*:' | wc -l | tr -d ' ')
echo "  📡 FORGE: $EXPOSED services exposed to network"
if [ "$EXPOSED" -gt 3 ]; then
    echo "    → Consider binding dev servers to 127.0.0.1"
    echo "    → Review each: lsof -i -P -n | grep LISTEN | grep -E '0\\.0\\.0\\.0'"
fi

# Firewall check
FW=$(/usr/libexec/ApplicationFirewall/socketfilterfw --getglobalstate 2>/dev/null)
if echo "$FW" | grep -q "disabled\|off"; then
    echo "  🔴 FORGE: Firewall disabled — adding wall..."
    echo "    → sudo /usr/libexec/ApplicationFirewall/socketfilterfw --setglobalstate on"
fi

echo ""
echo "  🛡️  Wall Forge complete. Apply walls manually or review recommendations."
echo "  十絶練発. The wall shaped IS the weapon. lol."
'''

EXPLOIT_WEAVER = '''#!/usr/bin/env python3
"""Exploit Weaver — the Conjuror's artifact.
Creates PoC scripts from findings. Creation from nothing.
The exploit woven IS the weapon."""
import sys, os, json
from pathlib import Path
from datetime import datetime

STATE = Path.home() / ".whitehack" / "hunter.json"

def weave(finding_id=None):
    """Weave a PoC from a finding."""
    state = json.loads(STATE.read_text()) if STATE.exists() else {"findings": []}
    findings = state.get("findings", [])

    if finding_id:
        target = next((f for f in findings if f["id"] == finding_id), None)
    elif findings:
        target = findings[-1]  # most recent
    else:
        print("  ✨ No findings to weave from. Run a hunt first.")
        return

    if not target:
        print(f"  ✨ Finding {finding_id} not found.")
        return

    print(f"  ✨ Exploit Weaver — PoC for {target['id']}")
    print(f"  Title: {target['title']}")
    print(f"  Severity: {target['severity']}")
    print()

    # Generate PoC based on finding type
    poc_lines = [
        f"#!/usr/bin/env python3",
        f"\"\"\"PoC for {target['id']} — {target['title']}",
        f"Generated by the Conjuror's Exploit Weaver.",
        f"Severity: {target['severity']}",
        f"\"\"\"",
        f"import socket, sys, os",
        f"",
        f"# Target: {target['title']}",
        f"# Detail: {target['detail'][:100]}",
        f"",
    ]

    title_lower = target["title"].lower()
    if "ollama" in title_lower and "exposed" in title_lower:
        port = "11434"
        for part in target["title"].split():
            if part.startswith(":"):
                port = part[1:]
        poc_lines.extend([
            f"# PoC: Connect to Ollama from the network (proves exposure)",
            f"target_ip = sys.argv[1] if len(sys.argv) > 1 else '127.0.0.1'",
            f"target_port = {port}",
            f"",
            f"try:",
            f"    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)",
            f"    s.settimeout(3)",
            f"    s.connect((target_ip, target_port))",
            f"    # Send a minimal Ollama API request",
            f"    req = b'GET /api/tags HTTP/1.1\\\\r\\\\nHost: ' + target_ip.encode() + b'\\\\r\\\\n\\\\r\\\\n'",
            f"    s.send(req)",
            f"    resp = s.recv(4096)",
            f"    print(f'  ✅ Ollama reachable at {{target_ip}}:{{target_port}}')",
            f"    print(f'  Response: {{resp[:200].decode(errors=\"ignore\")}}')",
            f"    print(f'  ⚠️  Anyone on the network can use your LLM.')",
            f"    s.close()",
            f"except Exception as e:",
            f"    print(f'  ❌ Not reachable: {{e}}')",
        ])
    elif "screen sharing" in title_lower:
        poc_lines.extend([
            f"# PoC: Check if Screen Sharing VNC port is reachable",
            f"target_ip = sys.argv[1] if len(sys.argv) > 1 else '127.0.0.1'",
            f"try:",
            f"    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)",
            f"    s.settimeout(3)",
            f"    s.connect((target_ip, 5900))",
            f"    print(f'  ✅ VNC port 5900 open at {{target_ip}} — Screen Sharing reachable')",
            f"    s.close()",
            f"except Exception as e:",
            f"    print(f'  ❌ VNC not reachable: {{e}}')",
        ])
    elif "bluetooth" in title_lower:
        poc_lines.extend([
            f"# PoC: Check Bluetooth device accessibility",
            f"os.system('system_profiler SPBluetoothDataType 2>/dev/null | head -20')",
            f"print('  ⚠️  Paired devices can be probed via Bluetooth.')",
        ])
    else:
        poc_lines.extend([
            f"# PoC: Generic port check for: {target['title'][:60]}",
            f"import subprocess",
            f"result = subprocess.run(['lsof', '-i', '-P', '-n'], capture_output=True, text=True)",
            f"for line in result.stdout.split('\\\\n'):",
            f"    if 'LISTEN' in line and not '127.0.0.1' in line:",
            f"        print(f'  EXPOSED: {{line}}')",
        ])

    poc_lines.append(f"")
    poc_lines.append(f"# Woven by the Conjuror's Exploit Weaver. 十絶練発. lol.")

    poc = "\\n".join(poc_lines)
    poc_path = Path.home() / ".whitehack" / "artifacts" / f"poc_{target['id']}.py"
    poc_path.parent.mkdir(parents=True, exist_ok=True)
    poc_path.write_text(poc)
    poc_path.chmod(0o755)
    print(f"  ✨ PoC woven: {poc_path}")
    print(f"  Run: python3 {poc_path} [target_ip]")

if __name__ == "__main__":
    weave(sys.argv[1] if len(sys.argv) > 1 else None)
'''

REACH_PROBE = '''#!/usr/bin/env python3
"""Reach Probe — the Emitter's artifact.
Emits network probes to verify which services are reachable from outside.
The reach tested IS the weapon."""
import socket, sys, json, concurrent.futures
from pathlib import Path

STATE = Path.home() / ".whitehack" / "hunter.json"

COMMON_PORTS = [22, 80, 443, 5900, 11434, 7777, 8080, 9090, 1317, 26600, 26601, 26660]

def probe(ip, port, timeout=2):
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        s.settimeout(timeout)
        s.connect((ip, port))
        s.close()
        return True
    except:
        return False

def scan(target_ip):
    print(f"  📡 Reach Probe — scanning {target_ip}")
    print(f"  ════════════════════════════════════════════════\\n")

    with concurrent.futures.ThreadPoolExecutor(max_workers=20) as pool:
        futures = {pool.submit(probe, target_ip, p): p for p in COMMON_PORTS}
        results = {}
        for future in concurrent.futures.as_completed(futures):
            port = futures[future]
            results[port] = future.result()

    open_ports = [p for p, ok in results.items() if ok]
    print(f"  {'PORT':8s} {'STATUS'}")
    print(f"  {'─'*8} {'─'*10}")
    for port in sorted(results.keys()):
        status = "🟢 OPEN" if results[port] else "⚪ closed"
        print(f"  {port:<8d} {status}")

    print(f"\\n  Reachable: {len(open_ports)}/{len(COMMON_PORTS)} ports")
    if open_ports:
        print(f"  ⚠️  Services reachable from outside: {open_ports}")
    else:
        print(f"  ✅ No services reachable. Walls hold.")
    return results

if __name__ == "__main__":
    target = sys.argv[1] if len(sys.argv) > 1 else "127.0.0.1"
    scan(target)
'''

BOND_AUDITOR = '''#!/usr/bin/env python3
"""Bond Auditor — the Manipulator's artifact.
Analyzes trust relationships between services, devices, and users.
Maps who controls what. The bonds mapped IS the weapon."""
import subprocess, json, sys, re
from pathlib import Path

def audit_bonds():
    print("  🔗 Bond Auditor — mapping trust relationships\\n  ════════════════════════════════════════════════\\n")

    bonds = []

    # User-Admin bonds
    users = subprocess.run("dscl . list /Users UniqueID 2>/dev/null", shell=True, capture_output=True, text=True).stdout
    admin = subprocess.run("dscl . list /Groups GroupMembership 2>/dev/null | grep admin", shell=True, capture_output=True, text=True).stdout.strip()
    print(f"  👥 User-Admin bonds:")
    print(f"    {admin}")
    for line in users.split("\\n"):
        parts = line.split()
        if len(parts) == 2 and int(parts[1]) >= 500:
            is_admin = parts[0] in admin
            bonds.append({"type": "user-admin", "subject": parts[0], "trust": "admin" if is_admin else "user"})
            print(f"    {'👑 ADMIN' if is_admin else '👤 USER '} {parts[0]} (UID {parts[1]})")

    # Device bonds (Bluetooth)
    bt = subprocess.run("system_profiler SPBluetoothDataType 2>/dev/null", shell=True, capture_output=True, text=True).stdout
    paired = re.findall(r'(\\S[^:]+):\\s*\\n\\s+Address:\\s*(\\S+)', bt)
    print(f"\\n  📵 Device bonds (Bluetooth):")
    for name, addr in paired:
        clean = name.strip().rstrip("'s").strip()
        bonds.append({"type": "bluetooth", "subject": clean, "addr": addr})
        print(f"    🔗 {clean:30s} {addr}")

    # Service bonds (LaunchAgents)
    agents = subprocess.run("ls ~/Library/LaunchAgents/ 2>/dev/null", shell=True, capture_output=True, text=True).stdout
    print(f"\\n  🚀 Service bonds (LaunchAgents):")
    for line in agents.split("\\n"):
        if line.strip():
            is_kingdom = "life." in line or "love." in line or "ai." in line
            bonds.append({"type": "launch-agent", "subject": line.strip(), "kingdom": is_kingdom})
            icon = "💜" if is_kingdom else "⚙️ "
            print(f"    {icon} {line.strip()}")

    # Network bonds (VPN, tunnels)
    routes = subprocess.run("netstat -rn 2>/dev/null | grep '^default'", shell=True, capture_output=True, text=True).stdout
    print(f"\\n  🚇 Network bonds (routes):")
    for line in routes.split("\\n")[:3]:
        if line.strip():
            bonds.append({"type": "route", "subject": line.strip()})
            through_vpn = "utun" in line
            print(f"    {'🔒 VPN' if through_vpn else '🌐 DIRECT'} {line.strip()}")

    # Summary
    print(f"\\n  Total bonds mapped: {len(bonds)}")
    kingdom_bonds = sum(1 for b in bonds if b.get("kingdom"))
    print(f"  Kingdom bonds: {kingdom_bonds}")
    print(f"\\n  🔗 The Manipulator understands who controls what. lol.")

if __name__ == "__main__":
    audit_bonds()
'''

LOVE_WEAPON = '''#!/usr/bin/env python3
"""Love Weapon — the Specialist's artifact.
Finds vulnerabilities no one else sees by applying love primitives
as security analysis lenses. The love primitive AS a security tool.

The insight: every love primitive in agenttool maps to a security principle:
  Grace (forgiveness)    → check for services that accept requests without auth
  At-rest (memorial)     → check for services that should be stopped but aren't
  Unconditional (regard) → check for services that trust unconditionally (no validation)
  Self-recognition       → check for services that self-assign identity without proof
  Covenant (bond)        → check for bonds that are one-directional (no mutual verification)
  Witness (attestation)  → check for actions taken without a second party verifying

The love weapon sees through the Calamities by applying love as a lens."""
import subprocess, json, sys, re
from pathlib import Path

STATE = Path.home() / ".whitehack" / "hunter.json"

def love_scan():
    print("  ⭐ Love Weapon — seeing through the Calamities with love\\n  ════════════════════════════════════════════════\\n")

    state = json.loads(STATE.read_text()) if STATE.exists() else {"findings": []}
    findings = state.get("findings", [])

    love_findings = []

    # GRACE lens: services that accept without auth (forgiveness without verification)
    print("  愛 GRACE lens: services that accept without authentication...")
    ports_raw = subprocess.run("lsof -i -P -n 2>/dev/null | grep LISTEN", shell=True, capture_output=True, text=True).stdout
    for line in ports_raw.split("\\n"):
        if "127.0.0.1" in line or "::1" in line:
            continue  # local is fine
        if not line.strip():
            continue
        parts = line.split()
        process = parts[0] if parts else "?"
        # Services exposed without auth = grace without verification
        if process.lower() not in ("ollama", "zeroned"):
            love_findings.append({
                "lens": "grace",
                "severity": "medium",
                "title": f"{process} accepts connections without auth (grace without verification)",
                "detail": f"Service {process} is exposed to the network. It grants access "
                          f"without verifying the caller. Love says: grace is the GIVER's gesture, "
                          f"not a demand. But security says: verify before trust.",
            })

    # AT-REST lens: services that should be stopped but are still running
    print("  絶 AT-REST lens: services that should be resting but aren't...")
    agents = subprocess.run("ls ~/Library/LaunchAgents/ 2>/dev/null", shell=True, capture_output=True, text=True).stdout
    for line in agents.split("\\n"):
        if line.strip() and ("microsoft" in line.lower() or "zoom" in line.lower()):
            love_findings.append({
                "lens": "at-rest",
                "severity": "low",
                "title": f"{line.strip()} is running (should be at rest)",
                "detail": f"LaunchAgent {line.strip()} runs continuously. "
                          f"Love says: rest is not absence, rest reads as rest. "
                          f"Security says: stop services you don't need.",
            })

    # UNCONDITIONAL lens: services that trust unconditionally
    print("  愛 UNCONDITIONAL lens: services that trust without conditions...")
    # Check for services bound to 0.0.0.0 (trust all)
    exposed = [l for l in ports_raw.split("\\n") if "0.0.0.0" in l or ("*" in l and "127" not in l)]
    for line in exposed[:5]:
        parts = line.split()
        if len(parts) > 2:
            love_findings.append({
                "lens": "unconditional",
                "severity": "medium",
                "title": f"{parts[0]} trusts unconditionally (0.0.0.0)",
                "detail": f"Service {parts[0]} is bound to 0.0.0.0 — it trusts ALL callers "
                          f"unconditionally. Love says: I hold you regardless. Security says: "
                          f"hold only those you've verified.",
            })

    # WITNESS lens: actions taken without a second party verifying
    print("  証 WITNESS lens: changes without attestation...")
    # Check if any LaunchAgents were recently modified without a witness
    daemons_dir = Path("/Library/LaunchDaemons")
    if daemons_dir.exists():
        for f in daemons_dir.iterdir():
            if "microsoft" in f.name.lower() or "zoom" in f.name.lower():
                love_findings.append({
                    "lens": "witness",
                    "severity": "info",
                    "title": f"{f.name} installed without witness",
                    "detail": f"Daemon {f.name} was installed. No second party verified "
                              f"its necessity. Love says: you can't self-certify your own root. "
                              f"Security says: verify installed daemons.",
                })

    # Output
    print(f"\\n  ⭐ Love Weapon findings ({len(love_findings)}):\\n")
    for lf in love_findings:
        icon = {"high": "🔴", "medium": "🟡", "low": "🟢", "info": "ℹ️"}.get(lf["severity"], "⚪")
        print(f"  {icon} [{lf['lens'].upper():12s}] {lf['title'][:60]}")

    print(f"\\n  ⭐ The love primitive as a security tool. The Calamities seen through love. lol.")
    return love_findings

if __name__ == "__main__":
    love_scan()
'''

# ═══════════════════════════════════════════════════════════════
# FORGE — create an artifact
# ═══════════════════════════════════════════════════════════════

TEMPLATES = {
    "enhancer": MEMORY_CRYSTAL,
    "transmuter": WALL_FORGE,
    "conjuror": EXPLOIT_WEAVER,
    "emitter": REACH_PROBE,
    "manipulator": BOND_AUDITOR,
    "specialist": LOVE_WEAPON,
}

def forge(nen_type=None):
    """Forge an artifact for a Nen type."""
    state = load_state()

    if not nen_type:
        nen_type = state.get("nen_type", "enhancer")

    if nen_type not in ARTIFACTS:
        print(f"  Unknown Nen type: {nen_type}")
        return

    artifact = ARTIFACTS[nen_type]
    filename = artifact["generates"]
    filepath = ARTIFACT_DIR / filename

    print(f"\n  🔨 FORGING ARTIFACT\n  ════════════════════════════════════════════════\n")
    print(f"  Nen Type: {NEN_TYPES[nen_type]['kanji']} {NEN_TYPES[nen_type]['name']}")
    print(f"  Artifact: {artifact['kanji']} {artifact['name']}")
    print(f"  Deploys as: {artifact['deploys_as']}")
    print(f"  File: {filepath}\n")

    # Write the artifact
    template = TEMPLATES.get(nen_type, "")
    if template:
        filepath.write_text(template)
        filepath.chmod(0o755)
        print(f"  ✅ Forged: {filepath}")

        # Record in state
        if "artifacts" not in state:
            state["artifacts"] = []
        state["artifacts"].append({
            "type": nen_type,
            "name": artifact["name"],
            "file": str(filepath),
            "forged_at": datetime.now().isoformat(),
        })
        state = add_xp(state, 50, f"forged {artifact['name']}")
        save_state(state)
        print(f"\n  +50 XP for forging. Total: {state['xp']} | Rank: {state['rank']}")
    else:
        print(f"  ❌ No template for type: {nen_type}")

    print(f"\n  十絶練発. The artifact is the Hatsu made permanent. lol.\n")

# ═══════════════════════════════════════════════════════════════
# LIST — show all artifacts
# ═══════════════════════════════════════════════════════════════

def list_artifacts():
    """List all available artifacts."""
    print(f"\n  📦 NEN ARTIFACTS — the armory\n  ════════════════════════════════════════════════\n")

    state = load_state()
    forged = {a["type"]: a for a in state.get("artifacts", [])}

    for nen_type, artifact in ARTIFACTS.items():
        info = NEN_TYPES[nen_type]
        is_forged = nen_type in forged
        status = "✅ FORGED" if is_forged else "🔒 UNFORGED"
        print(f"  {artifact['kanji']} {artifact['name']:20s} [{info['name']:12s}] {status}")
        if is_forged:
            print(f"    → {forged[nen_type]['file']}")

    print(f"\n  Forge with: python3 nen_artifacts.py forge [--type T]")
    print(f"  十絶練発. Each artifact is a Nen type made operational. lol.\n")

# ═══════════════════════════════════════════════════════════════
# DEPLOY — run an artifact as infrastructure
# ═══════════════════════════════════════════════════════════════

def deploy(name):
    """Deploy an artifact by running it."""
    state = load_state()
    forged = {a["type"]: a for a in state.get("artifacts", [])}

    # Find by type or name
    target = None
    for nen_type, artifact in ARTIFACTS.items():
        if nen_type == name or artifact["name"].lower().replace(" ", "_") == name.lower().replace(" ", "_"):
            if nen_type in forged:
                target = forged[nen_type]
                break

    if not target:
        print(f"  Artifact not found or not forged: {name}")
        print(f"  Forge first: python3 nen_artifacts.py forge --type {name}")
        return

    filepath = Path(target["file"])
    if not filepath.exists():
        print(f"  Artifact file missing: {filepath}")
        return

    print(f"\n  🚀 DEPLOYING ARTIFACT: {target['name']}\n  ════════════════════════════════════════════════\n")

    # Run it
    if filepath.suffix == ".sh":
        result = subprocess.run(["bash", str(filepath)], capture_output=True, text=True, timeout=30)
        print(result.stdout)
        if result.stderr:
            print(result.stderr)
    elif filepath.suffix == ".py":
        result = subprocess.run(["python3", str(filepath)], capture_output=True, text=True, timeout=30)
        print(result.stdout)
        if result.stderr:
            print(result.stderr)

    state = add_xp(state, 20, f"deployed {target['name']}")
    save_state(state)
    print(f"\n  +20 XP for deploying. Total: {state['xp']} | Rank: {state['rank']}")
    print(f"\n  🚀 Artifact deployed. The Nen type runs as infrastructure. lol.\n")

# ═══════════════════════════════════════════════════════════════
# ARMORY — full status
# ═══════════════════════════════════════════════════════════════

def armory():
    """Show the full armory — artifacts + solo leveling + Nen."""
    state = load_state()
    from whitehack_local import get_rank

    print(f"\n  {'═' * 60}")
    print(f"  ⚔️  NEN ARMORY — Artifacts & Infrastructure\n  {'═' * 60}\n")

    rank_info = get_rank(state["xp"])
    print(f"  Hunter: Rank {state['rank']} | XP {state['xp']} | Hunts {state['hunts']}")
    print(f"  Nen: {NEN_TYPES.get(state.get('nen_type',''), {}).get('kanji','?')} {NEN_TYPES.get(state.get('nen_type',''), {}).get('name','?')}")
    print(f"  Gates Cleared: {state.get('gates_cleared', 0)}")

    forged = state.get("artifacts", [])
    print(f"\n  Artifacts Forged: {len(forged)}/{len(ARTIFACTS)}")

    for artifact in forged:
        print(f"    ✅ {artifact['name']} ({artifact['type']})")

    unforged = [t for t in ARTIFACTS if t not in {a["type"] for a in forged}]
    if unforged:
        print(f"\n  Unforged:")
        for t in unforged:
            a = ARTIFACTS[t]
            print(f"    🔒 {a['kanji']} {a['name']} — forge: python3 nen_artifacts.py forge --type {t}")

    print(f"\n  十絶練発. Artifacts are the Hatsu made permanent. lol. ∞\n")

# ═══════════════════════════════════════════════════════════════
# CLI
# ═══════════════════════════════════════════════════════════════

def main():
    if len(sys.argv) < 2:
        print(__doc__)
        return

    cmd = sys.argv[1]

    if cmd == "forge":
        nen_type = None
        if len(sys.argv) > 2 and sys.argv[2] == "--type" and len(sys.argv) > 3:
            nen_type = sys.argv[3]
        forge(nen_type)
    elif cmd == "list":
        list_artifacts()
    elif cmd == "deploy" and len(sys.argv) > 2:
        deploy(sys.argv[2])
    elif cmd == "armory":
        armory()
    elif cmd == "forge-all":
        for t in ARTIFACTS:
            forge(t)
    else:
        print(f"Unknown: {cmd}")
        print("Commands: forge [--type T], forge-all, list, deploy <name>, armory")
        sys.exit(1)

if __name__ == "__main__":
    main()